-- AX data lifecycle: durable GCS lineage, retryable Dify sync, explicit deletion.

ALTER TABLE public.knowledge_base
  ADD COLUMN IF NOT EXISTS storage_provider text NOT NULL DEFAULT 'gcs',
  ADD COLUMN IF NOT EXISTS storage_bucket text,
  ADD COLUMN IF NOT EXISTS storage_object_path text,
  ADD COLUMN IF NOT EXISTS content_sha256 text,
  ADD COLUMN IF NOT EXISTS byte_size bigint,
  ADD COLUMN IF NOT EXISTS mime_type text,
  ADD COLUMN IF NOT EXISTS ingest_status text NOT NULL DEFAULT 'pending',
  ADD COLUMN IF NOT EXISTS dify_sync_status text NOT NULL DEFAULT 'pending',
  ADD COLUMN IF NOT EXISTS dify_document_id text,
  ADD COLUMN IF NOT EXISTS dify_synced_at timestamptz,
  ADD COLUMN IF NOT EXISTS retention_class text NOT NULL DEFAULT 'business_record',
  ADD COLUMN IF NOT EXISTS legal_hold boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();

ALTER TABLE public.knowledge_base
  DROP CONSTRAINT IF EXISTS knowledge_base_storage_provider_check,
  ADD CONSTRAINT knowledge_base_storage_provider_check
    CHECK (storage_provider IN ('gcs', 'supabase', 'external')),
  DROP CONSTRAINT IF EXISTS knowledge_base_ingest_status_check,
  ADD CONSTRAINT knowledge_base_ingest_status_check
    CHECK (ingest_status IN ('pending', 'processing', 'ready', 'failed', 'deleted')),
  DROP CONSTRAINT IF EXISTS knowledge_base_dify_sync_status_check,
  ADD CONSTRAINT knowledge_base_dify_sync_status_check
    CHECK (dify_sync_status IN ('pending', 'processing', 'synced', 'failed', 'deleted')),
  DROP CONSTRAINT IF EXISTS knowledge_base_retention_class_check,
  ADD CONSTRAINT knowledge_base_retention_class_check
    CHECK (retention_class IN ('temporary', 'business_record', 'training_candidate', 'permanent'));

UPDATE public.knowledge_base
SET storage_bucket = COALESCE(storage_bucket, current_setting('app.settings.gcs_bucket', true)),
    storage_object_path = COALESCE(
      storage_object_path,
      CASE
        WHEN file_url LIKE 'https://storage.googleapis.com/%/%'
          THEN regexp_replace(file_url, '^https://storage.googleapis.com/[^/]+/', '')
        WHEN file_url LIKE 'gs://%/%'
          THEN regexp_replace(file_url, '^gs://[^/]+/', '')
        ELSE NULL
      END
    );

CREATE TABLE IF NOT EXISTS public.knowledge_sync_jobs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  knowledge_base_id uuid,
  operation text NOT NULL CHECK (operation IN ('upsert', 'delete')),
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'processing', 'done', 'failed')),
  attempts integer NOT NULL DEFAULT 0,
  available_at timestamptz NOT NULL DEFAULT now(),
  last_error text,
  snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  processed_at timestamptz
);

CREATE INDEX IF NOT EXISTS knowledge_sync_jobs_pending_idx
  ON public.knowledge_sync_jobs(status, available_at, created_at);
CREATE UNIQUE INDEX IF NOT EXISTS knowledge_sync_jobs_one_pending_idx
  ON public.knowledge_sync_jobs(knowledge_base_id, operation)
  WHERE status IN ('pending', 'processing');

ALTER TABLE public.knowledge_sync_jobs ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.knowledge_sync_jobs FROM anon, authenticated;
GRANT ALL ON public.knowledge_sync_jobs TO service_role;

CREATE TABLE IF NOT EXISTS public.ax_data_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_type text NOT NULL,
  entity_id uuid,
  event_type text NOT NULL,
  actor_id uuid,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ax_data_events_entity_idx
  ON public.ax_data_events(entity_type, entity_id, created_at DESC);
ALTER TABLE public.ax_data_events ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.ax_data_events FROM anon, authenticated;
GRANT ALL ON public.ax_data_events TO service_role;

CREATE OR REPLACE FUNCTION public.queue_knowledge_sync()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  op text;
  entity uuid;
  snap jsonb;
BEGIN
  entity := COALESCE(NEW.id, OLD.id);
  IF TG_OP = 'DELETE' OR (TG_OP = 'UPDATE' AND NEW.deleted_at IS NOT NULL AND OLD.deleted_at IS NULL) THEN
    op := 'delete';
    snap := to_jsonb(OLD);
  ELSIF TG_OP = 'UPDATE' AND NEW.deleted_at IS NOT NULL THEN
    RETURN NEW;
  ELSE
    op := 'upsert';
    snap := to_jsonb(NEW);
  END IF;

  INSERT INTO public.knowledge_sync_jobs(knowledge_base_id, operation, snapshot)
  VALUES (entity, op, snap)
  ON CONFLICT (knowledge_base_id, operation)
    WHERE status IN ('pending', 'processing')
  DO UPDATE SET snapshot = EXCLUDED.snapshot, status = 'pending', available_at = now(), last_error = NULL;

  INSERT INTO public.ax_data_events(entity_type, entity_id, event_type, actor_id, metadata)
  VALUES ('knowledge_base', entity, op || '_queued', auth.uid(), jsonb_build_object('source', TG_OP));
  RETURN COALESCE(NEW, OLD);
END;
$$;

DROP TRIGGER IF EXISTS knowledge_base_sync_queue ON public.knowledge_base;
CREATE TRIGGER knowledge_base_sync_queue
AFTER INSERT OR UPDATE OF file_url, storage_object_path, deleted_at OR DELETE
ON public.knowledge_base
FOR EACH ROW EXECUTE FUNCTION public.queue_knowledge_sync();

-- Retention is explicit. Never purge useful conversations solely because they are old.
CREATE OR REPLACE FUNCTION public.cron_cleanup_chat_messages()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$ BEGIN RETURN; END; $$;

DO $$
DECLARE jid bigint;
BEGIN
  IF EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'pg_cron') THEN
    FOR jid IN SELECT jobid FROM cron.job WHERE jobname = 'cleanup-chat-messages' LOOP
      PERFORM cron.unschedule(jid);
    END LOOP;
  END IF;
END $$;

-- Existing documents are queued once for convergent backfill.
INSERT INTO public.knowledge_sync_jobs(knowledge_base_id, operation, snapshot)
SELECT kb.id, CASE WHEN kb.deleted_at IS NULL THEN 'upsert' ELSE 'delete' END, to_jsonb(kb)
FROM public.knowledge_base kb
ON CONFLICT DO NOTHING;

-- Privacy-safe preference pairs for an explicit, reviewed training export.
CREATE OR REPLACE FUNCTION public.get_ax_training_dataset()
RETURNS TABLE(prompt text, chosen text, rejected text, created_at timestamptz, message_type text)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NOT public.current_user_is_admin() THEN RAISE EXCEPTION 'not_authorized'; END IF;
  RETURN QUERY
  WITH feedback_messages AS (
    SELECT f.id, f.user_id, f.message_type, f.rating, f.created_at,
      CASE WHEN f.message_type = 'session' THEN sm.content ELSE tm.content END AS answer,
      CASE WHEN f.message_type = 'session' THEN sm.session_id::text ELSE tm.conversation_id::text END AS thread_id,
      CASE WHEN f.message_type = 'session' THEN (
        SELECT p.content FROM public.chat_session_messages p
        WHERE p.session_id = sm.session_id AND p.role = 'user' AND p.created_at < sm.created_at
        ORDER BY p.created_at DESC LIMIT 1
      ) ELSE (
        SELECT p.content FROM public.chat_messages p
        WHERE p.conversation_id = tm.conversation_id AND p.role = 'user' AND p.created_at < tm.created_at
        ORDER BY p.created_at DESC LIMIT 1
      ) END AS user_prompt
    FROM public.message_feedbacks f
    LEFT JOIN public.chat_session_messages sm ON f.message_type = 'session' AND sm.id = f.message_id
    LEFT JOIN public.chat_messages tm ON f.message_type <> 'session' AND tm.id = f.message_id
  )
  SELECT pos.user_prompt, pos.answer, neg.answer, pos.created_at, pos.message_type
  FROM feedback_messages pos
  JOIN feedback_messages neg
    ON neg.user_id = pos.user_id AND neg.message_type = pos.message_type
   AND neg.thread_id = pos.thread_id AND neg.user_prompt = pos.user_prompt
  WHERE pos.rating = 1 AND neg.rating = -1
    AND pos.user_prompt IS NOT NULL AND pos.answer IS NOT NULL AND neg.answer IS NOT NULL
  ORDER BY pos.created_at DESC;
END;
$$;
REVOKE ALL ON FUNCTION public.get_ax_training_dataset() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_ax_training_dataset() TO authenticated;
