-- Phase 2-1: RAG 검색 품질 계측 (docs/reports/system-upgrade-plan-2026-07.md)
--
-- 어떤 질의가 어떤 청크를 어떤 유사도로 가져왔는지 기록한다.
-- 이 로그가 있어야 한국어 FTS 교체·threshold 조정·리랭커 확장의 효과를
-- 숫자로 비교할 수 있고, message_feedbacks 와 조인해 "부정 피드백을 받은
-- 답변이 어떤 근거를 썼는지" 역추적할 수 있다.

CREATE TABLE IF NOT EXISTS public.rag_retrieval_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  -- 검색 경로: company_documents | work_cases | dify_bridge_documents | dify_bridge_cases | rag_eval
  source text NOT NULL,
  -- 질의 원문(200자 절단 — DLP 통과 후 텍스트만 들어옴)
  query_text text,
  result_count integer NOT NULL DEFAULT 0,
  top_similarity double precision,
  -- 상위 결과 요약: [{id, label(file_name/title), similarity}]
  results jsonb,
  latency_ms integer,
  user_id uuid,
  extra jsonb
);

CREATE INDEX IF NOT EXISTS rag_retrieval_logs_created_idx
  ON public.rag_retrieval_logs (created_at);
CREATE INDEX IF NOT EXISTS rag_retrieval_logs_source_created_idx
  ON public.rag_retrieval_logs (source, created_at);

ALTER TABLE public.rag_retrieval_logs ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.rag_retrieval_logs FROM anon, authenticated;
GRANT ALL ON public.rag_retrieval_logs TO service_role;

-- 보존 90일 (token_logs 와 동일 정책)
DO $do$
DECLARE
  jid bigint;
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'pg_cron') THEN
    RAISE NOTICE 'pg_cron 미설치 — rag_retrieval_logs 보존 잡을 건너뜁니다.';
    RETURN;
  END IF;
  FOR jid IN SELECT jobid FROM cron.job WHERE jobname = 'truncate-rag-retrieval-logs' LOOP
    PERFORM cron.unschedule(jid);
  END LOOP;
  PERFORM cron.schedule(
    'truncate-rag-retrieval-logs',
    '10 3 * * *',
    $job$DELETE FROM public.rag_retrieval_logs WHERE created_at < now() - interval '90 days';$job$
  );
END $do$;
