-- Seed marketplace extensions: Plugin / MCP / Skill / Public Data
-- Each row is a separate INSERT to avoid parser truncation on large multi-value inserts.

-- ── Plugin: 날씨 정보 ────────────────────────────────────────────────────────
insert into public.plugins (plugin_id, name, description, provider, category, extension_type, required_scopes, auth_type, auth_header_name, connection_mode, config_schema, manifest, tool_function_name, endpoint_url, is_active, enabled, approval_status, version)
values ('nh.plugin.weather', '날씨 정보', '기상청 API를 통해 현재 날씨와 단기 예보를 조회합니다.', 'KMA', 'utility', 'plugin', '["weather.read"]', 'api_key', 'Authorization', 'admin_shared', '{"type":"object","properties":{"city":{"type":"string","description":"도시명 (예: 서울)"},"days":{"type":"integer","minimum":1,"maximum":7}}}', '{"icon":"🌤️","tools":[{"name":"nh_get_weather","description":"지정 도시의 날씨와 예보를 반환합니다."}]}', 'nh_get_weather', 'builtin://weather', true, true, 'approved', '1.0.0')
on conflict (plugin_id) do update set name=excluded.name, description=excluded.description, provider=excluded.provider, category=excluded.category, extension_type=excluded.extension_type, required_scopes=excluded.required_scopes, config_schema=excluded.config_schema, manifest=excluded.manifest, tool_function_name=excluded.tool_function_name, is_active=excluded.is_active, enabled=excluded.enabled, approval_status=excluded.approval_status, version=excluded.version;

-- ── Plugin: Jira ─────────────────────────────────────────────────────────────
insert into public.plugins (plugin_id, name, description, provider, category, extension_type, required_scopes, auth_type, auth_header_name, connection_mode, config_schema, manifest, tool_function_name, endpoint_url, is_active, enabled, approval_status, version)
values ('nh.plugin.jira', 'Jira 이슈 조회', 'Atlassian Jira의 이슈를 검색하고 상태를 확인합니다. 프로젝트 키와 JQL 쿼리를 지원합니다.', 'Atlassian', 'project_management', 'plugin', '["jira.read","jira.write"]', 'bearer', 'Authorization', 'per_user', '{"type":"object","properties":{"jira_url":{"type":"string"},"project_key":{"type":"string"}}}', '{"icon":"🎫","tools":[{"name":"nh_search_jira_issues","description":"JQL로 이슈를 검색합니다."},{"name":"nh_get_jira_issue","description":"이슈 상세 정보를 가져옵니다."}]}', 'nh_search_jira_issues', 'builtin://jira', true, true, 'approved', '2.1.0')
on conflict (plugin_id) do update set name=excluded.name, description=excluded.description, provider=excluded.provider, category=excluded.category, extension_type=excluded.extension_type, required_scopes=excluded.required_scopes, config_schema=excluded.config_schema, manifest=excluded.manifest, tool_function_name=excluded.tool_function_name, is_active=excluded.is_active, enabled=excluded.enabled, approval_status=excluded.approval_status, version=excluded.version;

-- ── Plugin: Slack ─────────────────────────────────────────────────────────────
insert into public.plugins (plugin_id, name, description, provider, category, extension_type, required_scopes, auth_type, auth_header_name, connection_mode, config_schema, manifest, tool_function_name, endpoint_url, is_active, enabled, approval_status, version)
values ('nh.plugin.slack', 'Slack 알림', 'Slack 채널에 메시지를 보내거나 최신 메시지를 가져옵니다.', 'Slack', 'communication', 'plugin', '["slack.send","slack.read"]', 'bearer', 'Authorization', 'per_user', '{"type":"object","properties":{"workspace":{"type":"string","description":"Slack 워크스페이스 URL"}}}', '{"icon":"💬","tools":[{"name":"nh_send_slack_message","description":"채널에 메시지를 전송합니다."},{"name":"nh_list_slack_channels","description":"채널 목록을 반환합니다."}]}', 'nh_send_slack_message', 'builtin://slack', true, true, 'approved', '1.3.0')
on conflict (plugin_id) do update set name=excluded.name, description=excluded.description, provider=excluded.provider, category=excluded.category, extension_type=excluded.extension_type, required_scopes=excluded.required_scopes, config_schema=excluded.config_schema, manifest=excluded.manifest, tool_function_name=excluded.tool_function_name, is_active=excluded.is_active, enabled=excluded.enabled, approval_status=excluded.approval_status, version=excluded.version;

-- ── Plugin: Google Calendar ──────────────────────────────────────────────────
insert into public.plugins (plugin_id, name, description, provider, category, extension_type, required_scopes, auth_type, auth_header_name, connection_mode, config_schema, manifest, tool_function_name, endpoint_url, is_active, enabled, approval_status, version)
values ('nh.plugin.google-calendar', 'Google Calendar', 'Google Calendar의 일정을 조회하고, 새 이벤트를 생성하거나 삭제합니다.', 'Google', 'productivity', 'plugin', '["calendar.read","calendar.write"]', 'bearer', 'Authorization', 'per_user', '{}', '{"icon":"📅","oauth":true,"tools":[{"name":"nh_list_calendar_events","description":"지정 기간의 일정을 조회합니다."},{"name":"nh_create_calendar_event","description":"새 일정을 생성합니다."}]}', 'nh_list_calendar_events', 'builtin://google-calendar', true, true, 'approved', '1.0.0')
on conflict (plugin_id) do update set name=excluded.name, description=excluded.description, provider=excluded.provider, category=excluded.category, extension_type=excluded.extension_type, required_scopes=excluded.required_scopes, config_schema=excluded.config_schema, manifest=excluded.manifest, tool_function_name=excluded.tool_function_name, is_active=excluded.is_active, enabled=excluded.enabled, approval_status=excluded.approval_status, version=excluded.version;

-- ── MCP: 파일시스템 ───────────────────────────────────────────────────────────
insert into public.plugins (plugin_id, name, description, provider, category, extension_type, required_scopes, auth_type, auth_header_name, connection_mode, config_schema, manifest, tool_function_name, endpoint_url, is_active, enabled, approval_status, version)
values ('nh.mcp.filesystem', '파일시스템 MCP', '로컬 또는 네트워크 파일시스템을 AI 채팅에서 직접 읽고 쓸 수 있도록 MCP 프로토콜로 연결합니다.', 'Community', 'developer', 'mcp', '["fs.read","fs.write"]', 'none', 'Authorization', 'per_user', '{"type":"object","required":["server_url"],"properties":{"server_url":{"type":"string","description":"MCP 서버 URL (예: http://localhost:3001)"},"allowed_paths":{"type":"array","items":{"type":"string"}}}}', '{"icon":"📁","mcp":true,"transport":"http"}', 'nh_mcp_filesystem', null, true, true, 'approved', '0.9.0')
on conflict (plugin_id) do update set name=excluded.name, description=excluded.description, provider=excluded.provider, category=excluded.category, extension_type=excluded.extension_type, required_scopes=excluded.required_scopes, config_schema=excluded.config_schema, manifest=excluded.manifest, tool_function_name=excluded.tool_function_name, is_active=excluded.is_active, enabled=excluded.enabled, approval_status=excluded.approval_status, version=excluded.version;

-- ── MCP: GitHub ──────────────────────────────────────────────────────────────
insert into public.plugins (plugin_id, name, description, provider, category, extension_type, required_scopes, auth_type, auth_header_name, connection_mode, config_schema, manifest, tool_function_name, endpoint_url, is_active, enabled, approval_status, version)
values ('nh.mcp.github', 'GitHub MCP', 'GitHub 레포지토리의 이슈, PR, 코드를 AI 채팅에서 조회하고 관리합니다.', 'GitHub', 'developer', 'mcp', '["github.read","github.write"]', 'bearer', 'Authorization', 'per_user', '{"type":"object","required":["server_url","token"],"properties":{"server_url":{"type":"string","description":"MCP 서버 URL"},"token":{"type":"string","description":"GitHub Personal Access Token"}}}', '{"icon":"🐙","mcp":true,"transport":"http","tools":["list_repos","get_issue","create_issue","list_prs","get_pr"]}', 'nh_mcp_github', null, true, true, 'approved', '1.0.0')
on conflict (plugin_id) do update set name=excluded.name, description=excluded.description, provider=excluded.provider, category=excluded.category, extension_type=excluded.extension_type, required_scopes=excluded.required_scopes, config_schema=excluded.config_schema, manifest=excluded.manifest, tool_function_name=excluded.tool_function_name, is_active=excluded.is_active, enabled=excluded.enabled, approval_status=excluded.approval_status, version=excluded.version;

-- ── MCP: 데이터베이스 ─────────────────────────────────────────────────────────
insert into public.plugins (plugin_id, name, description, provider, category, extension_type, required_scopes, auth_type, auth_header_name, connection_mode, config_schema, manifest, tool_function_name, endpoint_url, is_active, enabled, approval_status, version)
values ('nh.mcp.database', '데이터베이스 MCP', 'PostgreSQL / MySQL 데이터베이스에 자연어로 쿼리하고 결과를 채팅에서 바로 확인합니다.', 'Community', 'data', 'mcp', '["db.read"]', 'bearer', 'Authorization', 'per_user', '{"type":"object","required":["server_url","connection_string"],"properties":{"server_url":{"type":"string","description":"MCP 서버 URL"},"connection_string":{"type":"string","description":"DB 연결 문자열"}}}', '{"icon":"🗄️","mcp":true,"transport":"http","tools":["run_query","list_tables","describe_table"]}', 'nh_mcp_database', null, true, true, 'approved', '0.7.2')
on conflict (plugin_id) do update set name=excluded.name, description=excluded.description, provider=excluded.provider, category=excluded.category, extension_type=excluded.extension_type, required_scopes=excluded.required_scopes, config_schema=excluded.config_schema, manifest=excluded.manifest, tool_function_name=excluded.tool_function_name, is_active=excluded.is_active, enabled=excluded.enabled, approval_status=excluded.approval_status, version=excluded.version;

-- ── Skill: 주간 업무 요약 ─────────────────────────────────────────────────────
insert into public.plugins (plugin_id, name, description, provider, category, extension_type, required_scopes, auth_type, auth_header_name, connection_mode, config_schema, manifest, tool_function_name, endpoint_url, is_active, enabled, approval_status, version)
values ('nh.skill.weekly-summary', '주간 업무 요약', '이번 주 처리한 업무 목록을 입력하면 보고서 형식의 주간 요약문을 자동 작성합니다.', 'NH Internal', 'productivity', 'skill', '[]', 'none', 'Authorization', 'admin_shared', '{}', '{"icon":"📝","prompt":"당신은 NH농협은행의 업무 보조 AI입니다. 사용자가 제공한 이번 주 업무 목록을 바탕으로 주간 업무 보고서를 작성해 주세요.\n\n**주간 업무 보고서**\n- 기간: {{이번 주 월~금}}\n- 작성자: {{이름}}\n\n### 주요 업무 실적\n{{각 업무 bullet point}}\n\n### 다음 주 예정\n{{예정 업무}}\n\n### 특이사항\n{{이슈, 리스크}}\n\n입력: {{업무 목록}}"}', 'nh_skill_weekly_summary', 'builtin://skill', true, true, 'approved', '1.0.0')
on conflict (plugin_id) do update set name=excluded.name, description=excluded.description, provider=excluded.provider, category=excluded.category, extension_type=excluded.extension_type, required_scopes=excluded.required_scopes, config_schema=excluded.config_schema, manifest=excluded.manifest, tool_function_name=excluded.tool_function_name, is_active=excluded.is_active, enabled=excluded.enabled, approval_status=excluded.approval_status, version=excluded.version;

-- ── Skill: 이메일 초안 ────────────────────────────────────────────────────────
insert into public.plugins (plugin_id, name, description, provider, category, extension_type, required_scopes, auth_type, auth_header_name, connection_mode, config_schema, manifest, tool_function_name, endpoint_url, is_active, enabled, approval_status, version)
values ('nh.skill.email-draft', '이메일 초안 작성', '수신자, 목적, 핵심 내용을 입력하면 공손하고 명확한 비즈니스 이메일 초안을 작성합니다.', 'NH Internal', 'communication', 'skill', '[]', 'none', 'Authorization', 'admin_shared', '{}', '{"icon":"✉️","prompt":"당신은 비즈니스 커뮤니케이션 전문가입니다. 아래 정보를 바탕으로 전문적인 한국어 이메일 초안을 작성해 주세요.\n\n- 수신자: {{수신자 이름 및 직위}}\n- 목적: {{이메일 목적}}\n- 핵심 내용: {{전달 내용}}\n- 톤: {{공식적/친근한/긴급}}\n\n제목: ...\n\n본문:\n...\n\n서명 포함"}', 'nh_skill_email_draft', 'builtin://skill', true, true, 'approved', '1.0.0')
on conflict (plugin_id) do update set name=excluded.name, description=excluded.description, provider=excluded.provider, category=excluded.category, extension_type=excluded.extension_type, required_scopes=excluded.required_scopes, config_schema=excluded.config_schema, manifest=excluded.manifest, tool_function_name=excluded.tool_function_name, is_active=excluded.is_active, enabled=excluded.enabled, approval_status=excluded.approval_status, version=excluded.version;

-- ── Skill: 코드 리뷰 ─────────────────────────────────────────────────────────
insert into public.plugins (plugin_id, name, description, provider, category, extension_type, required_scopes, auth_type, auth_header_name, connection_mode, config_schema, manifest, tool_function_name, endpoint_url, is_active, enabled, approval_status, version)
values ('nh.skill.code-review', '코드 리뷰 요청', '코드 스니펫을 붙여넣으면 버그, 성능, 보안 관점의 리뷰 코멘트를 생성합니다.', 'NH Internal', 'developer', 'skill', '[]', 'none', 'Authorization', 'admin_shared', '{}', '{"icon":"🔍","prompt":"당신은 시니어 소프트웨어 엔지니어입니다. 아래 코드를 검토해 주세요.\n\n검토 항목:\n1. 버그: 잠재적 오류, 엣지케이스\n2. 성능: 불필요한 연산, N+1\n3. 보안: SQL 인젝션, XSS, 인증 누락\n4. 가독성: 변수명, 함수 분리\n5. 개선 제안\n\n코드:\n```\n{{code}}\n```\n\n각 항목에 심각도(높음/중간/낮음)를 표시해 주세요."}', 'nh_skill_code_review', 'builtin://skill', true, true, 'approved', '1.1.0')
on conflict (plugin_id) do update set name=excluded.name, description=excluded.description, provider=excluded.provider, category=excluded.category, extension_type=excluded.extension_type, required_scopes=excluded.required_scopes, config_schema=excluded.config_schema, manifest=excluded.manifest, tool_function_name=excluded.tool_function_name, is_active=excluded.is_active, enabled=excluded.enabled, approval_status=excluded.approval_status, version=excluded.version;

-- ── Skill: 회의록 요약 ────────────────────────────────────────────────────────
insert into public.plugins (plugin_id, name, description, provider, category, extension_type, required_scopes, auth_type, auth_header_name, connection_mode, config_schema, manifest, tool_function_name, endpoint_url, is_active, enabled, approval_status, version)
values ('nh.skill.meeting-minutes', '회의록 요약', '회의 내용을 텍스트로 붙여넣으면 결정사항, 액션아이템, 다음 일정이 포함된 회의록을 생성합니다.', 'NH Internal', 'productivity', 'skill', '[]', 'none', 'Authorization', 'admin_shared', '{}', '{"icon":"📋","prompt":"당신은 회의록 작성 전문가입니다. 아래 회의 내용을 구조화된 회의록으로 작성해 주세요.\n\n**회의록**\n- 일시: {{회의 일시}}\n- 참석자: {{참석자 목록}}\n- 안건: {{주요 안건}}\n\n### 주요 논의 사항\n{{핵심 내용}}\n\n### 결정사항\n{{확정된 사항}}\n\n### 액션아이템\n| 담당자 | 할 일 | 기한 |\n|--------|--------|------|\n{{테이블}}\n\n### 다음 회의\n{{일정 및 안건}}\n\n회의 내용:\n{{meeting_content}}"}', 'nh_skill_meeting_minutes', 'builtin://skill', true, true, 'approved', '1.0.0')
on conflict (plugin_id) do update set name=excluded.name, description=excluded.description, provider=excluded.provider, category=excluded.category, extension_type=excluded.extension_type, required_scopes=excluded.required_scopes, config_schema=excluded.config_schema, manifest=excluded.manifest, tool_function_name=excluded.tool_function_name, is_active=excluded.is_active, enabled=excluded.enabled, approval_status=excluded.approval_status, version=excluded.version;

-- ── Public Data: 기상청 날씨 예보 ─────────────────────────────────────────────
insert into public.plugins (plugin_id, name, description, provider, category, extension_type, required_scopes, auth_type, auth_header_name, connection_mode, config_schema, manifest, tool_function_name, endpoint_url, is_active, enabled, approval_status, version)
values ('nh.public-data.weather-forecast', '기상청 날씨 예보', '기상청 공공데이터포털 API를 통해 전국 단기·중기 날씨 예보를 조회합니다.', 'KMA / data.go.kr', 'public_data', 'public_data', '["public_data.read"]', 'api_key', 'Authorization', 'per_user', '{"type":"object","required":["api_key"],"properties":{"api_key":{"type":"string","description":"공공데이터포털 API 인증키"}}}', '{"icon":"⛅","portal_url":"https://www.data.go.kr/data/15084084/openapi.do","tools":[{"name":"nh_get_kma_weather","description":"기상청 단기 예보를 가져옵니다."}]}', 'nh_get_kma_weather', 'builtin://kma-weather', true, true, 'approved', '1.0.0')
on conflict (plugin_id) do update set name=excluded.name, description=excluded.description, provider=excluded.provider, category=excluded.category, extension_type=excluded.extension_type, required_scopes=excluded.required_scopes, config_schema=excluded.config_schema, manifest=excluded.manifest, tool_function_name=excluded.tool_function_name, is_active=excluded.is_active, enabled=excluded.enabled, approval_status=excluded.approval_status, version=excluded.version;

-- ── Public Data: 국가통계포털 (KOSIS) ────────────────────────────────────────
insert into public.plugins (plugin_id, name, description, provider, category, extension_type, required_scopes, auth_type, auth_header_name, connection_mode, config_schema, manifest, tool_function_name, endpoint_url, is_active, enabled, approval_status, version)
values ('nh.public-data.stats-korea', '국가통계포털 (KOSIS)', '통계청 KOSIS API로 국내 주요 통계 데이터를 조회합니다. 인구, 경제, 금융 관련 지표를 지원합니다.', 'Statistics Korea', 'public_data', 'public_data', '["public_data.read"]', 'api_key', 'Authorization', 'per_user', '{"type":"object","required":["api_key"],"properties":{"api_key":{"type":"string","description":"KOSIS API 인증키"}}}', '{"icon":"📊","portal_url":"https://kosis.kr/openapi/","tools":[{"name":"nh_search_kosis_stats","description":"KOSIS 통계표를 검색하고 데이터를 가져옵니다."}]}', 'nh_search_kosis_stats', 'builtin://kosis', true, true, 'approved', '1.0.0')
on conflict (plugin_id) do update set name=excluded.name, description=excluded.description, provider=excluded.provider, category=excluded.category, extension_type=excluded.extension_type, required_scopes=excluded.required_scopes, config_schema=excluded.config_schema, manifest=excluded.manifest, tool_function_name=excluded.tool_function_name, is_active=excluded.is_active, enabled=excluded.enabled, approval_status=excluded.approval_status, version=excluded.version;
